name: "Publish Container Image"

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish in addition to `latest`"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          install: true
          platforms: |
            linux/amd64
            linux/arm64

      - name: Compute Tags
        id: compute-tags
        run: |
          prefix="ghcr.io/jaegertracing/spark-dependencies/spark-dependencies"
          tags="$prefix:latest"
          
          if [[ -n "${{ inputs.tag }}" ]]; then
            tags="$tags,$prefix:${{ inputs.tag }}"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            release=$(echo ${{ github.ref }} | sed 's/refs\/tags\///g')
            tags="$tags,$prefix:$release"
          fi

          echo "Computed tags for publication: $tags"
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: ${{ steps.compute-tags.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64
